### PR TITLE
 My Work(Adding some css and js part) #1

### PR DESCRIPTION
**Pull request by zeel-codder**
Hi, My Name is zeel. and i am new in open sources.
Iadd some css and js part in your web sited;
I also change Dark to light button in responsive 500px part.
This is look.
Screenshot (382)

### CODE REVIEW

**Review by ManudeQuevedo — CHANGES_REQUESTED** [review]
Why did you add those latest CSS Styles?

**Comment by zeel-codder** [comment]
Not a very big reason.
I take part in hectorberfest and I  am very new in open source.
I learning how to make web sit responsive. there for I tried to change some style and make the thing batter and also add some JavaScript part.

**Comment by ManudeQuevedo** [comment]
Also, what was the purpose of adding this line to the conditional that stores the latest status on the theme so that next time the user access the website it remembers whether it was on Light or Dark mode?

`document.getElementById("mode_text").innerText = "Lite Mode"`

I do not see any of your changes reflected, I see the new HTML, CSS, and JS but the browser is not rendering it at all.

**Comment by zeel-codder** [comment]
because, I change for max-500px width device only.

**Comment by zeel-codder** [comment]
I know ,I not do much work in your web site. Sorry for wasting your time. 
Next, time I do much batter works.

**Comment by ManudeQuevedo** [comment]
Like, I never meant it was not good work my friend, I was just curious about the changes you made. Sorry if I made you feel like it was not ok ;) But it's really good that you proposed your own idea of improvement.

**Pull request closed without merging**
